name = "Wynncraft 101"
author = "aninuscsalas"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "568e8244fdf3b11b45f76141ad6b4acd5bb94b28da4995638b53aaa042816071"

[versions]
forge = "45.1.16"
minecraft = "1.19.4"
